### ISSUE TITLE
add search field to main page 

### ISSUE THREAD

**Issue by marcel-epp** [marcel-epp/capstone-tripapp#1]
## Value proposition
As a user
I want to be able to select my preferences
In order to get suggestions for my next trip.
## Description
- Multiple checkboxes or dropdown with select options to select personal preferences like: 
- budget
- choose a region
- choose an activity

## Acceptance criteria
- When you visit the page, you should see the preferences that are available to choose. When the user submits the preferences, the matching destinations will be displayed in a list.
- If there are no matches, the user gets a message "nothing found, please change your preferences".

## Tasks
- Build a dummy database (/lib/db.js) to fetch data.
- Build a form component to submit the preferences.
- Include the form component in the index.js.
- Create a handlesubmit function to get the submited data.
- Compare the database it with the preferences from the user.
- Display the results in a list under the form component.

**Comment by MerleMak** [comment]
How about:
## Value proposition
How about:
As a traveller
I want to be able to find a trip that match my preferences
In order to save time in finding my dream destinations.

## Description
The description should not contain any text, only the wireframe. The bulletpoint you did put in the description actually belong in the Acceptance criteria :)

## Acceptance criteria
How about:
- [ ] When visiting the page, the preferences that are available to choose are displayed in several input fields:
   - Multiple checkboxes for the type of trip
   - A dropdown to select personal budget
   - A dropdown to choose a region
- [ ] When the user submits the preferences, the matching destinations will be displayed in a list.
- [ ] If there are no matches, the user gets a message "nothing found, please change your preferences".

## Tasks
Compare the database with the preferences from the user.
-> This tasks is actually a lot more complex than that. As you have several different input fields, you have to filter through the dataarray and filter for all of the preferences. Just so you keep this in mind :)


Nice job! Keep it going 🚀

**Comment by JanineGlaser** [comment]
@MerleMak 
Thank you for your suggestions,
we changed it up. :)
