### ISSUE TITLE
improve DB and refine search results

### ISSUE THREAD

**Issue by JanineGlaser** [marcel-epp/capstone-tripapp#11]
## Value proposition
As a developer
I want to add more  than one activity to the places
In order to get more matches

## Description
each object in the db can have more than one value in the activity key
each details displays all the possible activities for the object

## Acceptance criteria
- [ ] DB Key "activities" can handle more than one activity

## Tasks
- [ ] refactor the DB to add more activities to the activity key
- [ ] refactor handleSubmit function to find all the activities in an  array

**Comment by gcode-de** [comment]
looking good!
