### ISSUE TITLE
Navigation menu for mobile and desktop

### ISSUE THREAD

**Issue by JeanetteSchwarz** [marcel-epp/capstone-tripapp#13]
## Value proposition
As a user
I want to navigate through the application
In order to visit the different pages 

## Description
![navbar](https://github.com/marcel-epp/capstone-tripapp/assets/155547505/a91de6ca-7848-4143-a8af-934a8bccba1e)

## Acceptance criteria
- [ ] The navigation menu is always visible, depending on the viewport (mobile/desktop). 
- [ ] The not required navbar is invisible
- [ ] The active page is highlighted

## Tasks
- [ ] create two navbars. One for the mobile version (footer), one for the desktop version (header).
- [ ] write mediaquerys depending on the viewport (mobile/desktop). 
- [ ] write a state to check wich page is activated
