### ISSUE TITLE
Favorite page with bookmark function

### ISSUE THREAD

**Issue by marcel-epp** [marcel-epp/capstone-tripapp#14]
## Value proposition
As a user
I want to bookmark my favorite places
In order to save them for later.
## Description
![7988DDB3-DF08-4E73-8A06-4C574BAAFA03](https://github.com/marcel-epp/capstone-tripapp/assets/155982642/7c73c038-c7f7-4417-acf2-5e196704e8b8)

## Acceptance criteria
- [ ] When the user clicks the favorite icon the icon should change it's
visual state (e. g. another color or image)
- [ ] When the user clicks the favorite icon again the icon should
change to its former style
- [ ] The user can click on the favorite icon endlessly and it will toggle
between both stylings
- [ ] Clicking the favorite-button on a non-favorite item saves it as a favorite
Clicking the favorite-button on a favorite item removes it from favorites
- [ ] All favorite are displayed on the favorites page
## Tasks
- [ ] Create a new page favourites.js that renders a list of all favorites
- [ ] Create a favorite icon/button that is displayed on the previewCard, spotlightCard as well as on the detailsCard
- [ ] Write a state for the favorite button
- [ ] Write a handlefavourite function that sets the state and prop the list with all favorites to the favorites page
