### ISSUE TITLE
static profile page

### ISSUE THREAD

**Issue by JanineGlaser** [marcel-epp/capstone-tripapp#15]
## Value proposition
As a developer
I want to give the user a profile page 
In order to be able to personalize the application 

## Description
![Screenshot 2024-03-06 at 16 07 17](https://github.com/marcel-epp/capstone-tripapp/assets/155562582/15cdecb2-7f26-4fe5-b55a-34c03c03c63e)

## Acceptance criteria
- [ ] The profile page should display the user's basic information such as name, profile picture, and any other relevant details like a short "about me" text
- [ ] I am able to click the profile page icon in the navbar.

## Tasks
- [ ] create page Profile.js
- [ ] build the username, profile picture, about me text. (for now these are static values)
