### ISSUE TITLE
US 9 - Add a styling to the site

### ISSUE THREAD

**Issue by marcel-epp** [marcel-epp/capstone-tripapp#19]
## Value proposition
As a developer
I want to deliver a good looking site
In order to have fun, to use the site.
## Description
![TravelApp](https://github.com/marcel-epp/capstone-tripapp/assets/155982642/dd1f0159-f54c-4e3c-a2af-69b63b1c06f9)

## Acceptance criteria
- [ ] The site should look similar to the figma design (see above)
- [ ] The site should work as before
- [ ] The site has mobile and desktop styled
## Tasks
- [ ] add css variables
- [ ] add css in the components
- [ ] add google fonts (here cabin)
- [ ] add fontawesome for icons
