### ISSUE TITLE
US 10 - Database cleanup 

### ISSUE THREAD

**Issue by marcel-epp** [marcel-epp/capstone-tripapp#20]
## Value proposition
As a developer
I want to overlook the database
In order to get better search results for the users.
## Description
- Pictures have to be static and not dynamic
- less activitys
- places have more activitys
- add another 5 places
- add star ranking from 1-5
## Acceptance criteria
- [ ] The results are easier to get. For now, no more than 3 tries to get a result.
- [ ] The picture is static. For now, a placeholder would be okay
## Tasks
- [ ] Add a placeholder under images and change the link from every item in the "database".
- [ ] Remove some activitys
- [ ] Assign more activitys to a place
- [ ] Add 5 more places
- [ ] Change the rating from 1-10 to 1-5. For now, no number higher than five.
