### ISSUE TITLE
US 11 - Database outsourcing

### ISSUE THREAD

**Issue by marcel-epp** [marcel-epp/capstone-tripapp#21]
## Value proposition
As a developer
I want to have a real database
In order to store information in it.
## Description
- Create a database on mongoDB and fetch the data
## Acceptance criteria
- [ ] After the outsourcing, the app should work as before
- [ ] Data can be fetched from the database
- [ ] The user can see, if the loading process takes longer
- [ ] If no data can be fetched, the user get an information, that there is a problem
## Tasks
- [ ] Create a database on mongoDB
- [ ] Create the collection and assign the keys, like in the db.js file
- [ ] Install SWR and use it to fetch the data
- [ ] Write the fetch function, and implement the info and error handling
- [ ] Get the placeholder image from images, or find a way to store images maybe on a third party cloudservice
