### ISSUE TITLE
US 12 - create a comment on details page

### ISSUE THREAD

**Issue by JeanetteSchwarz** [marcel-epp/capstone-tripapp#22]
## Value proposition
As a user
I want to add comments to a place i visited
In order to help others with my experience

## Description
<img width="292" alt="Bildschirmfoto 2024-03-11 um 09 35 21" src="https://github.com/marcel-epp/capstone-tripapp/assets/155547505/e43c466d-30e9-4f24-8619-050fab7c14e5">

## Acceptance criteria
- [ ] On the details page the user finds an input field where he can leave a comment
- [ ] after submitting the comment is displayed beneath the information and the form

## Tasks
- [ ] create a form with three input fields: name, email and comment
- [ ] create a submit button
- [ ] create a Comment Card, that is rendert on the details page

**Comment by MareikeFla** [comment]
Sounds good to me! Have just one question. 
Where and how is the comment stored after submitting it?
