### ISSUE TITLE
US 13 - Delete own comments

### ISSUE THREAD

**Issue by JeanetteSchwarz** [marcel-epp/capstone-tripapp#23]
## Value proposition
As a user
I want the option to delete my own comments
In order to delete it, if I am not happy with it

## Description
<img width="329" alt="Bildschirmfoto 2024-03-11 um 10 10 14" src="https://github.com/marcel-epp/capstone-tripapp/assets/155547505/fa2c30b9-a3df-43a3-9cdb-8c14629c1dc2">

## Acceptance criteria
- [ ] By pushing the delete button, the comment gets deleted

## Tasks
- [ ] Add a delete button 
- [ ] write the handle-delete-function
