### ISSUE TITLE
US 15 - Create Login for users

### ISSUE THREAD

**Issue by JanineGlaser** [marcel-epp/capstone-tripapp#27]
## Value proposition
As a prospective user,
I want to have a secure and easy login system
In order to access the platform's features and personalized content.

## Description
<img width="205" alt="Screenshot 2024-03-11 at 17 21 13" src="https://github.com/marcel-epp/capstone-tripapp/assets/155562582/041d8c24-57db-4007-9bd9-0ef3a08e545c">

## Acceptance criteria
- [ ] I should be able to access the login page from the platform's homepage.
- [ ] The login page should contain buttons for either sign in or create an account.
- [ ] clicking on the sign in button input fields for entering my username/email and password should show up
- [ ] If I enter invalid credentials, I should receive a clear error message indicating the issue (e.g., incorrect username/email or 
- [ ] The platform should comply with relevant security standards and regulations to safeguard user data and privacy.passwor

## Tasks
- [ ] List the tasks that need to be performed within the dev team
