### ISSUE TITLE
Random Spotlight

### ISSUE THREAD

**Issue by JeanetteSchwarz** [marcel-epp/capstone-tripapp#3]
## Value proposition

As a user
I want to get random suggestions
in order to get inspired for new destinations

## Description

![Surprise](https://github.com/marcel-epp/capstone-tripapp/assets/155547505/0576ae47-d11d-4f78-9663-ce988e7d2844)

## Acceptance criteria

- When hitting the "Surprise me" Button on the search form, a random result is displayed

## Tasks

- [ ] Create a "Surprise me"-Button on the search form.
- [ ] Write a handleSurprise function, that returns a random result
- [ ] Reuse the Card-Component

**Comment by avoesen** [comment]
tiptop!
