### ISSUE TITLE
US 16 - Create new places as a user

### ISSUE THREAD

**Issue by marcel-epp** [marcel-epp/capstone-tripapp#33]
## Value proposition
As a user
I want to post my own places
In order to share my visited places
## Description
In the profile of the user, the user can post a new place with:
- [ ] A title (name of the place)
- [ ] A link to an image url
- [ ] The user can choose from the available activities
- [ ] Can add a description text
- [ ] Can add his own review 
## Acceptance criteria
- [ ] The user must log in to create a place
- [ ] The options from the description are available
- [ ] - [ ] The user have a list in his profile where he sees his created places
## Tasks
- [ ] Use the model Place, and check if this needs changes
- [ ] Create a form under Forms for the place to submit
- [ ] Add the logic to the api route
- [ ] Build a list to display the created places under profile

**Comment by NikRoe** [comment]
LGTM
