### ISSUE TITLE
US 17 - Edit own places as a user

### ISSUE THREAD

**Issue by marcel-epp** [marcel-epp/capstone-tripapp#34]
## Value proposition
As a user
I want to edit my created places
In order to keep the information up to date
## Description
- [ ] The user can edit his created places under the profile. There should be a list of his created places.
## Acceptance criteria
- [ ] The user can see his created places. If he has no places created, there should be an empty list.
- [ ] The user can edit all Informations (Name, Image Url, Description, Review) and update this information
## Tasks
- [ ] Make the creation Form for places reusable
- [ ] Add the logic to the routes endpoint

**Comment by NikRoe** [comment]
LGTM
