### ISSUE TITLE
US 20 - User can choose is favorite activities

### ISSUE THREAD

**Issue by marcel-epp** [marcel-epp/capstone-tripapp#37]
## Value proposition
As a user
I want to display my favorite activities on my profile page
In order to show others (later) what i'm interested in.
## Description
The user can choose from the available activities, and can add them to his profile. He can edit this list, or delete this list.
## Acceptance criteria
- [ ] The user sees an List under his profiles with activities.
- [ ] The user can select which activities he likes.
- [ ] The activities are displayed under his own profile
## Tasks
- [ ] ...
