### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by marcel-epp** [marcel-epp/capstone-tripapp#4]
## Value proposition
As a user
I want to add more different preferences
In order to get more detailed search results.
## Description
![DA9EA9E8-0823-4024-872D-56C46DAA015C](https://github.com/marcel-epp/capstone-tripapp/assets/155982642/783d89eb-60e6-459c-80e0-d6982ee3547e)

## Acceptance criteria
- [ ] When the user visits the page, you should see the preferences that are available to choose. Multiple checkboxes and dropdowns.
- [ ] When the user submits the preferences, the matching destinations will be displayed in a list.
- [ ] If there are no matches, the user gets a message "nothing found, please change your preferences".
## Tasks
- [ ] rewrite the handleSubmit function
