### ISSUE TITLE
US 21 - Adding places only for authentificated users

### ISSUE THREAD

**Issue by JeanetteSchwarz** [marcel-epp/capstone-tripapp#44]
## Value proposition
As a developer
I want to block the "add places"-function for unauthentificated users
In order to make it a benefit for my users

## Description
- Only users who are logged in can add new places

## Acceptance criteria
- [ ] you have to sign in to open the form for adding new places.
- [ ] if not signed in, a messages appears "Please sign in".
- [ ] all new places are connected to their author.
- [ ] all new places are displayed in the profile

## Tasks
- [ ] Link the create function to the user.
- [ ] reuse parts of the "add a comment"-code
- [ ] reuse the preview card component to display
