### ISSUE TITLE
US 22 - image upload for users

### ISSUE THREAD

**Issue by JeanetteSchwarz** [marcel-epp/capstone-tripapp#45]
## Value proposition
As a user
I want to upload new images to my created places
In order to give a better overview

## Description

- image upload via Cloudinary

## Acceptance criteria
- [ ] Within the "Add places"-form is an image upload field.
- [ ] the image is added to Cloudinary and MongoDB
- [ ] it is displayed in all the cards

## Tasks
- [ ] Add an upload field to the "Add places"-form.
- [ ] adapt the the handlesubmit function if necessary
- [ ] make sure all the data is correctly imported to the database
