### ISSUE TITLE
US 23 - Scroll to top button

### ISSUE THREAD

**Issue by JeanetteSchwarz** [marcel-epp/capstone-tripapp#46]
## Value proposition
As a user
I want to have a scroll-to-top-button on the page
In order not to have to scroll the whole page up manually

## Description
<img width="406" alt="Bildschirmfoto 2024-03-21 um 15 37 58" src="https://github.com/marcel-epp/capstone-tripapp/assets/155547505/a23d9405-4f13-41ca-8497-b83f916e8a37">

## Acceptance criteria
- [ ] The button is always visible on the homepage
- [ ] when the button is clicked, the side scrolls up automatically

## Tasks
- [ ] create a button
- [ ] make the button always visible on the homepage
- [ ] write a handlescroll-function
