### ISSUE TITLE
Edit image on own places

### ISSUE THREAD

**Issue by JeanetteSchwarz** [marcel-epp/capstone-tripapp#52]
## Value proposition
As a user
I want to edit images on my created places
In order to show another one

## Description
- Make images changeable on created places

## Acceptance criteria
- [ ] when editing a place, you can also upload a new image
- [ ] image is uploaded to cloudinary
- [ ] if the user does not upload a new image, the actual image will remain

## Tasks
- [ ] implement an upload function for images into the editing functions
- [ ] make sure to adjust the backend route to mongoDB

**Comment by stellanw** [comment]
Good Job!
