### ISSUE TITLE
US 25 - Profile pages visible for all

### ISSUE THREAD

**Issue by JeanetteSchwarz** [marcel-epp/capstone-tripapp#53]
## Value proposition
As a user
I want to visit the profile page of a user
In order to see more informations about the person

## Description
- The user's profile page is visible for all

## Acceptance criteria
- [ ] you can click on the name of a user (author) either on a comment or on a created place to see the user's profile page
- [ ] on the details page of a place the user who created it, is displayed

## Tasks
- [ ] implement the author's name on the details page
- [ ] make the author's name clickable 
- [ ] create dynamic routes for the different users

**Comment by alex96dev** [comment]
LGTM!
