### ISSUE TITLE
US 28 - About me text on profile

### ISSUE THREAD

**Issue by JeanetteSchwarz** [marcel-epp/capstone-tripapp#56]
## Value proposition
As a user
I want to add an "about me"-text on my profile page
In order to tell something about myself

## Description
<img width="228" alt="Bildschirmfoto 2024-03-28 um 14 21 37" src="https://github.com/marcel-epp/capstone-tripapp/assets/155547505/94676307-61e0-4038-b6bb-b47a3abccb5a">

## Acceptance criteria
- [ ] the user can add an "About me-Text" at his/her profile page
- [ ] this text is displayed on the profile page

## Tasks
- [ ] create a form with a textarea where the user can add some text
- [ ] write a handlesubmit-function to get the input and make sure it is added into the database
- [ ] adjust the user-model
- [ ] create a delete button where the user can delete the text
